Added task field for column of kanban board
SoftEng701-Group5/assignment1 pull request #239
Opened 2021-04-07 00:26 UTC by Pranavan10

**Describe the issue**
Currently, the kanban board is hardcoded. In order for the board to be connected to firebase, a field must be created to specify which column the task belongs to.

**Describe the solution**
A field (Kanban_Column) has been added upon the creation of a task to be used to specify which column it belongs to.
Upon creation, the column field is set to null.

Resolves #180

2021-04-08 00:46 UTC, Jennak21 approved these changes
LGTM 👍

2021-04-10 09:05 UTC, kcho9906 requested changes
I don't think package-lock.json should be included in this pull request as you are not making any changes to the modules. I believe we are addressing the package-lock file changing in many pull requests in a separate issue. 

Aside from that, everything looks fine to me!

2021-04-11 04:36 UTC, Pranavan10 commented
> I don't think package-lock.json should be included in this pull request as you are not making any changes to the modules. I believe we are addressing the package-lock file changing in many pull requests in a separate issue.
> 
> Aside from that, everything looks fine to me!

removed changes of package-lock

2021-04-12 00:35 UTC, kcho9906 approved these changes

2021-04-12 00:47 UTC, merged