Issue #171: Implemented feedback alerts for login/signup failures.
SoftEng701-Group5/assignment1 pull request #251
Opened 2021-04-09 07:06 UTC by vkoil

**Describe the issue**

- The user should be advised as to the nature of any errors encountered during the login/signup process.

**Describe the solution**

- Routed Firebase authentication errors to the signup handler to display as an alert on failure.
- Displayed a separate alert for the login handler to also indicate that one or both credentials were entered incorrectly.

2021-04-12 00:49 UTC, Pranavan10 requested changes
No modules have been changed, so package-lock should not be added in this pr

2021-04-12 11:39 UTC, Denijar approved these changes
Looks good. The signup process is much more usable now with these error messages.

2021-04-15 00:26 UTC, sannan06 approved these changes

2021-04-16 10:17 UTC, Chuppay approved these changes
Looks good to me!

2021-04-17 00:28 UTC, merged