Change the Notes to Description
SoftEng701-Group5/assignment1 pull request #258
Opened 2021-04-14 16:43 UTC by Jigao-Zeng

---
name: Pull Request to fix issue #190
about: change the "Notes" title to "Description" in the task.
title: 'Change the Notes to Description '
labels:
assignees: 'Jigao Zeng'
---

**Describe the issue**
When adding a task it asks for a description but when displaying a task it displays what was written under notes. This cause inconsistency in naming and can confuse user

**Describe the solution**
Change the title of "Notes" to "Description" to make it consistent.

2021-04-14 21:42 UTC, dikunong requested changes
Just a small typo to fix :)

2021-04-14 21:42 UTC, dikunong commented on src/components/current-task/CurrentTaskNotes.jsx
> +        <span className="current-task-notes__title">Discription</span>
Nit: Description, not Discription :)

2021-04-15 00:14 UTC, dikunong approved these changes
LGTM!

2021-04-15 00:52 UTC, kcho9906 approved these changes

2021-04-16 08:36 UTC, bbqnvd approved these changes
Quick and easy. Nice.

2021-04-16 08:46 UTC, merged